force-app/main/default/objects/Library_Book__c/Library_Book__c.object-meta.xml
<CustomObject>
    <description>This object represents the books available in the library</description>
    <label>Library Book</label>
    <nameField>
        <label>Library Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Library_Book__c/fields/Available_Copies__c.field-meta.xml
<CustomField>
    <fullName>Available_Copies__c</fullName>
    <label>Available Copies</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Library_Book_Loan__c/Library_Book_Loan__c.object-meta.xml
<CustomObject>
    <description>This object represents loaned books to contacts</description>
    <label>Library Book Loan</label>
    <nameField>
        <label>Library Book Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Book Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Library_Book_Loan__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Book</label>
    <referenceTo>Library_Book__c</referenceTo>
    <relationshipLabel>Library Book Loans</relationshipLabel>
    <relationshipName>Library_Book_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Library_Book_Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Library Book Loans</relationshipLabel>
    <relationshipName>Library_Book_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Library_Book_Loan__c/fields/Loan_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_End_Date__c</fullName>
    <label>Loan End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LibraryService.cls
public with sharing class LibraryService {

    public class NoAvailableCopiesException extends Exception {}

    @AuraEnabled
    public static List<Library_Book__c> searchBooks(String searchTerm) {
        List<List<SObject>> searchResults = [
            FIND :('*' + searchTerm + '*') IN ALL FIELDS
            RETURNING Library_Book__c (Id, Title__c, Author__c, Available_Copies__c)
        ];
        return (List<Library_Book__c>) searchResults[0];
    }

    @AuraEnabled
    public static void loanBook(Id bookId, Id borrowerId, Integer numberOfCopies, Date loanEndDate) {
        if (numberOfCopies <= 0) {
            throw new NoAvailableCopiesException(Label.NoCopiesError);
        }

        Library_Book_Loan__c newLoan = new Library_Book_Loan__c(
            Borrower__c = borrowerId,
            Book__c = bookId,
            Loan_Start_Date__c = Date.today(),
            Loan_End_Date__c = loanEndDate
        );

        insert newLoan;
    }
}